curl http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv -OutFile $PSScriptRoot\data\Advertising.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Auto.data -OutFile $PSScriptRoot\data\Auto.data
curl http://www-bcf.usc.edu/~gareth/ISL/Auto.csv -OutFile $PSScriptRoot\data\Auto.csv
curl http://www-bcf.usc.edu/~gareth/ISL/College.csv -OutFile $PSScriptRoot\data\College.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Ch10Ex11.csv -OutFile $PSScriptRoot\data\Ch10Ex11.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Credit.csv -OutFile $PSScriptRoot\data\Credit.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Income1.csv -OutFile $PSScriptRoot\data\Income1.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Income2.csv -OutFile $PSScriptRoot\data\Income2.csv
curl http://www-bcf.usc.edu/~gareth/ISL/Heart.csv -OutFile $PSScriptRoot\data\Heart.csv
